language: python
sudo: no
python:
  - 3.4
  - 3.5
  - 3.6
install:
  # - pip install .
  - pip install coveralls
script: pytest
after_success:
  - coverage run --source=PyFields setup.py pytest
  - coveralls
